### PR TITLE
motd implementation

### PR DESCRIPTION
**Pull request by mnaray**
- create message of the day
- make motd an embed
- set certain schedule to 8am

### CODE REVIEW

**Review by sanqro — COMMENTED** [review]
:+1:

**Review by sanqro — CHANGES_REQUESTED** [review]
:+1:

**Review by sanqro — APPROVED** [review]
:+1:

**Review by RelxOff — APPROVED** [review]
👍

**Comment by sanqro** [comment]
@mnaray please fix this merge conflict :smile:

**Pull request merged**
